-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 16:44:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table type_personne
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS type_personne (
  id_type_personne SERIAL PRIMARY KEY,
  nom_type_personne VARCHAR(45) NOT NULL
)


-- -----------------------------------------------------
-- Table personne
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS personne (
  id_personne SERIAL,
  nom_personne VARCHAR(45) NOT NULL,
  prenom_personne VARCHAR(45) NOT NULL,
  date_n_personne DATE NULL,
  type_personne_id_type_personne INT NOT NULL,
  email VARCHAR(90) NOT NULL,
  mdp VARCHAR(255) NULL,
  membre_comite INT NOT NULL,
  sup_hierarchique INT NOT NULL,
  PRIMARY KEY (id_personne),
  CONSTRAINT fk_personne_type_personne1
    FOREIGN KEY (type_personne_id_type_personne)
    REFERENCES type_personne (id_type_personne)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table type_activite_excep
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS type_activite_excep (
  id_type_activite_excep SERIAL,
  nom_type_activite_excep VARCHAR(45) NULL,
  duree_max_type_activite_excep INT NOT NULL,
  duree_min_type_activite_excep INT NULL,
  personne_id_personne INT NULL,
  quota_demandes INT DEFAULT(50),
  PRIMARY KEY (id_type_activite_excep),
  CONSTRAINT fk_type_activite_excep_personne1
    FOREIGN KEY (personne_id_personne)
    REFERENCES personne (id_personne)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table type_etat_validation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS type_etat_validation (
  id_type_etat_validation SERIAL,
  nom_etat VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_type_etat_validation))


-- -----------------------------------------------------
-- Table demande_de_derogation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS demande_de_derogation (
  id_demande_de_derogation SERIAL,
  date_demande_de_derogation TIMESTAMP NOT NULL,
  date_debut_demande_de_derogation TIMESTAMP NOT NULL,
  date_fin_demande_de_derogation TIMESTAMP NOT NULL,
  montant_remuneration_demande_de_derogation DECIMAL(10) NULL DEFAULT 0,
  personne_qui_demande_id_personne INT NOT NULL,
  type_activite_excep_id_type_activite_excep INT NOT NULL,
  type_etat_validation_id_type_etat_validation INT NOT NULL,
  PRIMARY KEY (id_demande_de_derogation),
  CONSTRAINT fk_demande_de_derogation_personne1
    FOREIGN KEY (personne_qui_demande_id_personne)
    REFERENCES personne (id_personne)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_demande_de_derogation_type_activite_excep1
    FOREIGN KEY (type_activite_excep_id_type_activite_excep)
    REFERENCES type_activite_excep (id_type_activite_excep)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_demande_de_derogation_type_etat_validation1
    FOREIGN KEY (type_etat_validation_id_type_etat_validation)
    REFERENCES type_etat_validation (id_type_etat_validation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table historique_etude_de_validation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS historique_etude_de_validation (
  id_historique_etude_de_validation SERIAL,
  date_etude_de_validation TIMESTAMP NOT NULL,
  demande_de_derogation_id_demande_de_derogation INT NOT NULL,
  type_etat_validation_id_type_etat_validation INT NOT NULL,
  personne_id_personne INT NOT NULL,
  PRIMARY KEY (id_historique_etude_de_validation),
  CONSTRAINT fk_etude_de_validation_demande_de_derogation1
    FOREIGN KEY (demande_de_derogation_id_demande_de_derogation)
    REFERENCES demande_de_derogation (id_demande_de_derogation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_historique_etude_de_validation_type_etat_validation1
    FOREIGN KEY (type_etat_validation_id_type_etat_validation)
    REFERENCES type_etat_validation (id_type_etat_validation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_historique_etude_de_validation_personne1
    FOREIGN KEY (personne_id_personne)
    REFERENCES personne (id_personne)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

